In [75]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://localhost:5432/math')

In [76]:
import pandas as pd
sql = "SELECT * from votes" 
df_votes= pd.read_sql_query(sql, engine)

In [77]:
df_votes.head()

   id  postid  votetypeid  userid creationdate  bountyamount
0   1       1           2     NaN   2010-07-20           NaN
1   2       1           2     NaN   2010-07-20           NaN
2   3       2           2     NaN   2010-07-20           NaN
3   4       2           2     NaN   2010-07-20           NaN
4   5       7           2     NaN   2010-07-20           NaN

In [78]:
import pandas as pd
sql_posts = "SELECT * from posts"
df_posts= pd.read_sql_query(sql_posts, engine)

In [79]:

# import datetime
# import matplotlib.pyplot as plt
# import numpy as np

# import plotly.plotly as py
# import plotly.tools as tls
# tls.set_credentials_file(username='ankothari', api_key='wAHcYidcpyWuQuVSLdJx')
# # Learn about API authentication here: https://plot.ly/python/getting-started
# # Find your api_key here: https://plot.ly/settings/api

# x = np.array([datetime.datetime(2014, i, 9) for i in range(1,13)])
# y = df_votes[df_votes['postid'] == 1].groupby(['postid', 'creationdate'])['votetypeid'].value_counts()

# plt.plot(x,y)
# plt.tight_layout()

# fig = plt.gcf()
# plotly_fig = tls.mpl_to_plotly( fig )

# py.iplot(plotly_fig, filename='mpl-time-series')

In [80]:
# took 5 years to get an accepted answer.
# is still active and getting answers? 
# is it still get upvotes after getting an accepted answer?

# activity after it has received an accepted answer ? 
# should we consider the upvotes received in the first yr, or uptil it got an accepted answer. 
# number of answers. If the number of answers is inceasing even after receiving an accepted answer then this questions seem good. 
# till the question receives an accepted answer
# after the question receives an accepted answer. 
# once an accepted answer has been received, does the rate of upvotes increases? I suppose it does.

# if the user doesnt like a question or doesnt like it, how do we suggest him a better question? What features do we select? 
# how do u compare questions to increase the likelihood of being selected by the user? 

# if you see the graph then in the first two years it receives a few upvotes, but then there has to be some signal that 
# can predict the future and thus we can start looking at questions that are only a few years old and are in have the same
# slope this old question has when it had started. 

# df = df_votes[(df_votes['postid']==19048) & (df_votes['votetypeid']==2)]
# d = df.groupby('date')['votetypeid'].value_counts()
# per = df.date.dt.to_period("Y")
# g = df.groupby(per)
# g['votetypeid'].value_counts()

df_votes['date'] = pd.to_datetime(df_votes['creationdate']).dt.year
df_votes.head()

   id  postid  votetypeid  userid creationdate  bountyamount  date
0   1       1           2     NaN   2010-07-20           NaN  2010
1   2       1           2     NaN   2010-07-20           NaN  2010
2   3       2           2     NaN   2010-07-20           NaN  2010
3   4       2           2     NaN   2010-07-20           NaN  2010
4   5       7           2     NaN   2010-07-20           NaN  2010

In [81]:
df_votes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7682668 entries, 0 to 7682667
Data columns (total 7 columns):
id              int64
postid          int64
votetypeid      int64
userid          float64
creationdate    datetime64[ns]
bountyamount    float64
date            int64
dtypes: datetime64[ns](1), float64(2), int64(4)
memory usage: 410.3 MB

In [82]:
# import pandas as pd
# sql_postlinks = "SELECT * from postlinks" 
# df_postlinks = pd.read_sql_query(sql_postlinks, engine)

In [83]:
# df_postlinks['date'] = pd.to_datetime(df_postlinks['creationdate']).dt.year
# df_postlinks.head()

In [84]:
# Maybe we need to rerank the questions. First we may have to get all the questions to the same level. 
# If a question is old then it has an added advantage of having more scores, answers and links. 
# Once a question has an accepted answer, it may seem that the question will have more upvotes and favorites
# and lesser answers. 
# So two questions, first check the time they were created. and then see them neck to neck. maybe we see other questions as well
# and compare a few of them neck to neck.

In [85]:
# if a question just 4-5 years old then we need to recalculate its score so that we move it the top. 
# We will have to consider the number of answers it has, the scores it has received, etc.

In [86]:
# Take the links into account as well. That is the score of the answers that linked here. But how do we find which answers contained a link
# we might have to parse it. 
# Maybe for now use the score of the questions.

In [87]:
# 76,745 questions on linear algebra
# How do u find which question to show and in what order? 
# rank the questions, give more importance to questions taking into time into consideration. 
# high score but no accepted answer yet. 
# there are questions which dont an accepted answer but are really have a very high score. I dont want to show them this
# sort of question anyway. Because this is an open ended answer.

In [88]:
# new_df = pd.merge(df_postlinks, df_posts,  how='left', left_on=['relatedpostid'], right_on = ['id'])

In [90]:
df_votes['year'] = df_votes['creationdate'].dt.year

In [91]:
df_votes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7682668 entries, 0 to 7682667
Data columns (total 8 columns):
id              int64
postid          int64
votetypeid      int64
userid          float64
creationdate    datetime64[ns]
bountyamount    float64
date            int64
year            int64
dtypes: datetime64[ns](1), float64(2), int64(5)
memory usage: 468.9 MB

In [92]:
df_votes['date'] = pd.to_datetime(df_votes['creationdate'])


df = df_votes[(df_votes['votetypeid']==2)]#(df_votes['postid']==668) &

In [93]:
df

,id,postid,votetypeid,userid,creationdate,bountyamount,date,year
0,1,1,2,NaN,2010-07-20,NaN,2010-07-20,2010
1,2,1,2,NaN,2010-07-20,NaN,2010-07-20,2010
2,3,2,2,NaN,2010-07-20,NaN,2010-07-20,2010
3,4,2,2,NaN,2010-07-20,NaN,2010-07-20,2010
4,5,7,2,NaN,2010-07-20,NaN,2010-07-20,2010
5,6,1,2,NaN,2010-07-20,NaN,2010-07-20,2010
6,7,5,2,NaN,2010-07-20,NaN,2010-07-20,2010
7,8,9,2,NaN,2010-07-20,NaN,2010-07-20,2010
8,9,3,2,NaN,2010-07-20,NaN,2010-07-20,2010
9,10,1,2,NaN,2010-07-20,NaN,2010-07-20,2010
10,11,7,2,NaN,2010-07-20,NaN,2010-07-20,2010
11,12,9,2,NaN,2010-07-20,NaN,2010-07-20,2010
13,14,9,2,NaN,2010-07-20,NaN,2010-07-20,2010
14,15,17,2,NaN,2010-07-20,NaN,2010-07-20,2010
15,16,14,2,NaN,2010-07-20,NaN,2010-07-20,2010
16,17,13,2,NaN,2010-07-20,NaN,2010-07-20,2010
17,18,13,2,NaN,2010-07-20,NaN,2010-07-20,2010
18,19,7,2,NaN,2010-07-20,NaN,2010-07-20,2010
19,20,9,2,NaN,2010-07-20,NaN,2010-07-20,2010
20,21,21,2,NaN,2010-07-20,NaN,2010-07-20,2010
21,22,15,2,NaN,2010-07-20,NaN,2010-07-20,2010
22,23,9,2,NaN,2010-07-20,NaN,2010-07-20,2010
24,25,17,2,NaN,2010-07-20,NaN,2010-07-20,2010
25,26,24,2,NaN,2010-07-20,NaN,2010-07-20,2010
26,27,26,2,NaN,2010-07-20,NaN,2010-07-20,2010
27,28,24,2,NaN,2010-07-20,NaN,2010-07-20,2010
28,29,28,2,NaN,2010-07-20,NaN,2010-07-20,2010
29,30,25,2,NaN,2010-07-20,NaN,2010-07-20,2010
30,31,23,2,NaN,2010-07-20,NaN,2010-07-20,2010
31,32,23,2,NaN,2010-07-20,NaN,2010-07-20,2010
...,...,...,...,...,...,...,...,...
7682628,8624303,2805988,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682629,8624304,1381569,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682630,8624305,2805967,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682632,8624307,2806050,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682633,8624308,2805359,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682635,8624310,2803903,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682638,8624313,487537,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682639,8624314,2806123,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682640,8624315,2806127,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682641,8624316,2803923,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682643,8624318,986884,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682644,8624319,2806129,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682645,8624320,2806111,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682646,8624321,1561262,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682648,8624323,2806106,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682651,8624326,1265913,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682652,8624327,1441031,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682653,8624328,2806133,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682654,8624329,2806135,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682655,8624330,2806138,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682656,8624331,2805872,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682657,8624332,2805944,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682658,8624333,2806127,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682660,8624335,2806139,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682661,8624336,2803903,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682662,8624337,2806139,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682664,8624339,1022848,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682665,8624340,1022808,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682666,8624341,2805647,2,NaN,2018-06-03,NaN,2018-06-03,2018
7682667,8624342,2666679,2,NaN,2018-06-03,NaN,2018-06-03,2018

In [94]:
d = df.groupby(['postid', "year"])['votetypeid']

In [95]:
v = df.groupby(['postid', "year"])['votetypeid'].value_counts()

In [96]:
values = v.keys().tolist()
counts = v.tolist()

In [97]:
n = pd.DataFrame(v.keys().tolist())

In [98]:
n.index.name = "id"

In [99]:
n.columns = ["post_id", "year", "votes"]

In [100]:
n['counts'] = counts

In [101]:
n.columns

Index(['post_id', 'year', 'votes', 'counts'], dtype='object')

In [102]:
df_year_votes = n.pivot(index='post_id', columns='year', values='counts')

In [103]:
df_year_votes.to_csv("df_year_votes", sep='\t')

In [104]:
votes = df_year_votes.sum(axis=1)

In [105]:
votes = votes.astype("int")

In [106]:
votes.shape, df_year_votes.shape

((1801057,), (1801057, 9))

In [107]:
df_year_votes

year     2010  2011  2012  2013  2014  2015  2016  2017  2018
post_id
1        19.0   4.0  10.0  23.0  22.0  12.0  14.0  20.0   9.0
2         4.0   1.0   3.0   3.0   7.0   4.0   3.0   3.0   NaN
3         7.0   5.0   6.0  11.0  16.0   8.0  14.0  23.0   5.0
4         2.0   NaN   NaN   1.0   NaN   NaN   2.0   2.0   NaN
5         9.0   5.0   4.0   6.0   8.0   3.0   5.0   7.0   3.0
6         5.0   6.0   7.0   5.0   5.0   2.0   3.0   5.0   3.0
7        25.0   9.0   4.0   5.0   8.0   7.0   1.0   8.0   4.0
8         6.0   4.0   3.0   7.0   1.0   3.0   1.0   4.0   4.0
9        33.0   9.0  16.0  20.0  18.0  15.0  15.0  19.0   6.0
10        2.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
11       14.0   NaN   NaN   NaN  58.0  66.0  57.0  43.0  20.0
13        3.0   1.0   NaN   NaN   NaN   NaN   1.0   1.0   NaN
14        2.0   1.0   NaN   NaN   NaN   NaN   2.0   1.0   NaN
15        7.0   5.0   NaN   1.0   1.0   2.0   1.0   3.0   1.0
16        9.0   4.0   NaN   NaN   2.0   2.0   1.0   2.0   2.0
17        9.0   2.0   1.0   1.0   1.0   NaN   3.0   2.0   3.0
18        2.0   1.0   NaN   1.0   1.0   1.0   NaN   4.0   NaN
19        6.0   4.0   2.0   6.0   5.0   1.0   2.0   1.0   NaN
20        5.0   2.0   1.0   2.0   1.0   2.0   2.0   5.0   NaN
21        1.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
22        6.0   NaN   NaN   2.0   1.0   NaN   1.0   2.0   1.0
23        6.0   2.0   NaN   3.0   3.0   4.0   NaN   NaN   NaN
24        2.0   1.0   NaN   NaN   NaN   NaN   NaN   1.0   1.0
25        5.0   1.0   NaN   4.0   2.0   NaN   NaN   NaN   NaN
26        1.0   1.0   NaN   NaN   NaN   NaN   NaN   1.0   1.0
27        1.0   1.0   2.0   NaN   2.0   1.0   1.0   NaN   NaN
28        2.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
29       10.0   1.0   8.0   3.0   3.0   1.0   1.0   5.0   2.0
30        2.0   2.0   NaN   6.0   4.0   4.0   5.0   3.0   1.0
31        4.0   2.0   1.0  10.0   4.0   3.0   4.0   4.0   2.0
...       ...   ...   ...   ...   ...   ...   ...   ...   ...
2806049   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806050   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806051   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0
2806052   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0
2806060   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806066   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806072   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0
2806075   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806079   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0
2806085   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806088   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806091   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806095   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806096   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806097   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806100   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0
2806101   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0
2806103   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806106   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806108   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806109   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806111   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806114   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806123   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806127   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0
2806129   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806133   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806135   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806138   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0
2806139   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0

[1801057 rows x 9 columns]

In [108]:
df_year_votes.fillna(0, inplace=True)

In [109]:
for column in df_year_votes.columns:
    df_year_votes[column] = df_year_votes[column].astype(int)

In [110]:
votes = df_year_votes.sum(axis=1)

In [111]:
votes.index

Int64Index([      1,       2,       3,       4,       5,       6,       7,
                  8,       9,      10,
            ...
            2806109, 2806111, 2806114, 2806123, 2806127, 2806129, 2806133,
            2806135, 2806138, 2806139],
           dtype='int64', name='post_id', length=1801057)

In [112]:
df_year_votes.index

Int64Index([      1,       2,       3,       4,       5,       6,       7,
                  8,       9,      10,
            ...
            2806109, 2806111, 2806114, 2806123, 2806127, 2806129, 2806133,
            2806135, 2806138, 2806139],
           dtype='int64', name='post_id', length=1801057)

In [113]:
upvotes = df_year_votes.sum(axis=1)

In [114]:
upvotes.shape

(1801057,)

In [115]:
df_year_votes

year     2010  2011  2012  2013  2014  2015  2016  2017  2018
post_id
1          19     4    10    23    22    12    14    20     9
2           4     1     3     3     7     4     3     3     0
3           7     5     6    11    16     8    14    23     5
4           2     0     0     1     0     0     2     2     0
5           9     5     4     6     8     3     5     7     3
6           5     6     7     5     5     2     3     5     3
7          25     9     4     5     8     7     1     8     4
8           6     4     3     7     1     3     1     4     4
9          33     9    16    20    18    15    15    19     6
10          2     0     0     0     0     0     0     0     0
11         14     0     0     0    58    66    57    43    20
13          3     1     0     0     0     0     1     1     0
14          2     1     0     0     0     0     2     1     0
15          7     5     0     1     1     2     1     3     1
16          9     4     0     0     2     2     1     2     2
17          9     2     1     1     1     0     3     2     3
18          2     1     0     1     1     1     0     4     0
19          6     4     2     6     5     1     2     1     0
20          5     2     1     2     1     2     2     5     0
21          1     0     0     0     0     0     0     0     0
22          6     0     0     2     1     0     1     2     1
23          6     2     0     3     3     4     0     0     0
24          2     1     0     0     0     0     0     1     1
25          5     1     0     4     2     0     0     0     0
26          1     1     0     0     0     0     0     1     1
27          1     1     2     0     2     1     1     0     0
28          2     0     0     0     0     0     0     0     0
29         10     1     8     3     3     1     1     5     2
30          2     2     0     6     4     4     5     3     1
31          4     2     1    10     4     3     4     4     2
...       ...   ...   ...   ...   ...   ...   ...   ...   ...
2806049     0     0     0     0     0     0     0     0     1
2806050     0     0     0     0     0     0     0     0     1
2806051     0     0     0     0     0     0     0     0     3
2806052     0     0     0     0     0     0     0     0     2
2806060     0     0     0     0     0     0     0     0     1
2806066     0     0     0     0     0     0     0     0     1
2806072     0     0     0     0     0     0     0     0     2
2806075     0     0     0     0     0     0     0     0     1
2806079     0     0     0     0     0     0     0     0     3
2806085     0     0     0     0     0     0     0     0     1
2806088     0     0     0     0     0     0     0     0     1
2806091     0     0     0     0     0     0     0     0     1
2806095     0     0     0     0     0     0     0     0     1
2806096     0     0     0     0     0     0     0     0     1
2806097     0     0     0     0     0     0     0     0     1
2806100     0     0     0     0     0     0     0     0     2
2806101     0     0     0     0     0     0     0     0     2
2806103     0     0     0     0     0     0     0     0     1
2806106     0     0     0     0     0     0     0     0     1
2806108     0     0     0     0     0     0     0     0     1
2806109     0     0     0     0     0     0     0     0     1
2806111     0     0     0     0     0     0     0     0     1
2806114     0     0     0     0     0     0     0     0     1
2806123     0     0     0     0     0     0     0     0     1
2806127     0     0     0     0     0     0     0     0     2
2806129     0     0     0     0     0     0     0     0     1
2806133     0     0     0     0     0     0     0     0     1
2806135     0     0     0     0     0     0     0     0     1
2806138     0     0     0     0     0     0     0     0     1
2806139     0     0     0     0     0     0     0     0     2

[1801057 rows x 9 columns]

In [116]:
df_year_votes['upvotes'] = df_year_votes.sum(axis=1)

In [117]:
df_year_votes.sort_values("upvotes", ascending=False, inplace=True)

In [124]:
df_year_votes.columns

Index([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 'upvotes'], dtype='object', name='year')

In [133]:
merged_year_posts = pd.merge(df_posts, df_year_votes,left_on=["id"], right_index=True)

In [143]:
merged_year_posts.set_index("id", inplace=True)

In [144]:
merged_year_posts.head()

,posttypeid,acceptedanswerid,parentid,creationdate,score,viewcount,body,owneruserid,lasteditoruserid,lasteditordisplayname,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,upvotes
id,,,,,,,,,,,,,,,,,,,,,
1,1,9.0,NaN,2010-07-20 19:09:27.200,136,7391.0,<p>Can someone explain to me how there can be ...,10.0,32803.0,user126,...,19,4,10,23,22,12,14,20,9,133
3,1,NaN,NaN,2010-07-20 19:12:14.353,99,57921.0,"<p><a href=""http://mathfactor.uark.edu/"">mathf...",29.0,498.0,user126,...,7,5,6,11,16,8,14,23,5,95
4,2,NaN,3.0,2010-07-20 19:14:10.603,7,NaN,"<p><a href=""http://www.bbc.co.uk/podcasts/seri...",31.0,NaN,None,...,2,0,0,1,0,0,2,2,0,7
5,1,7.0,NaN,2010-07-20 19:18:01.250,47,9920.0,<p>I have read a few proofs that $\sqrt{2}$ is...,38.0,327363.0,user242,...,9,5,4,6,8,3,5,7,3,50
6,1,281.0,NaN,2010-07-20 19:20:00.543,40,3814.0,"<p>I'm looking for a nice, quick online graphi...",41.0,39567.0,user126,...,5,6,7,5,5,2,3,5,3,41

In [148]:
merged_year_posts.loc[21209]

posttypeid                                                               2
acceptedanswerid                                                       NaN
parentid                                                             21199
creationdate                                    2011-02-09 17:05:55.190000
score                                                                 1140
viewcount                                                              NaN
body                     <p>Historically, when Leibniz conceived of the...
owneruserid                                                            742
lasteditoruserid                                                    133781
lasteditordisplayname                                                 None
lasteditdate                                    2017-09-15 20:01:41.010000
lastactivitydate                                2017-09-15 20:01:41.010000
title                                                                 None
tags                                                                  None
answercount                                                            NaN
commentcount                                                            16
favoritecount                                                          NaN
closeddate                                                             NaT
communityowneddate                                                     NaT
2010                                                                     0
2011                                                                   155
2012                                                                   156
2013                                                                   205
2014                                                                   133
2015                                                                   133
2016                                                                   133
2017                                                                   132
2018                                                                    63
upvotes                                                               1110
Name: 21209, dtype: object

In [149]:
df_year_votes.index

Int64Index([  21209,   54568,  733754,   71874,  379927,   74383,   21199,
             379930,  734790,  199688,
            ...
            1811928,  302421, 1811932, 1811933, 1811937, 1075457, 1811940,
            1811941,  552156,  334437],
           dtype='int64', name='post_id', length=1801057)

In [54]:
# joined = df_year_votes.join(df_posts, how="left")

In [55]:
# joined.head()

,2010,2011,2012,2013,2014,2015,2016,2017,2018,upvotes,...,lasteditordisplayname,lasteditdate,lastactivitydate,title,tags,answercount,commentcount,favoritecount,closeddate,communityowneddate
post_id,,,,,,,,,,,,,,,,,,,,,
21209,0,155,156,205,133,133,133,132,63,1110,...,None,NaT,2011-02-25 14:32:59.027,None,None,NaN,0.0,NaN,NaT,NaT
54568,0,307,175,169,129,117,85,78,33,1093,...,None,NaT,2011-08-31 21:56:25.397,None,None,NaN,0.0,NaN,NaT,NaT
733754,0,0,0,0,452,181,154,135,84,1006,...,None,2014-07-21 20:22:32.900,2014-07-21 20:22:32.900,None,None,NaN,0.0,NaN,NaT,NaT
71874,0,162,116,198,209,260,0,0,0,945,...,None,NaT,2011-11-09 00:52:18.227,None,None,NaN,6.0,NaN,NaT,NaT
379927,0,0,0,378,154,138,133,77,37,917,...,None,2013-07-07 14:09:30.653,2013-07-07 14:09:30.653,Complex integral $\frac {1}{1+z}$,<complex-analysis><integration>,0.0,6.0,NaN,NaT,NaT

In [56]:
# df_posts

,id,posttypeid,acceptedanswerid,parentid,creationdate,score,viewcount,body,owneruserid,lasteditoruserid,lasteditordisplayname,lasteditdate,lastactivitydate,title,tags,answercount,commentcount,favoritecount,closeddate,communityowneddate
0,1,1,9.0,NaN,2010-07-20 19:09:27.200,136,7391.0,<p>Can someone explain to me how there can be ...,10.0,32803.0,user126,2018-03-01 19:53:22.017,2018-03-17 12:34:06.470,What Does it Really Mean to Have Different Kin...,<elementary-set-theory><intuition><infinity><faq>,9.0,0,41.0,NaT,NaT
1,3,1,NaN,NaN,2010-07-20 19:12:14.353,99,57921.0,"<p><a href=""http://mathfactor.uark.edu/"">mathf...",29.0,498.0,user126,2012-07-31 13:58:15.730,2018-06-04 02:31:46.080,List of interesting math podcasts?,<soft-question><big-list><online-resources>,17.0,3,62.0,NaT,2010-07-20 20:35:23.263
2,4,2,NaN,3.0,2010-07-20 19:14:10.603,7,NaN,"<p><a href=""http://www.bbc.co.uk/podcasts/seri...",31.0,NaN,None,NaT,2010-07-20 19:14:10.603,None,None,NaN,1,NaN,NaT,2010-07-20 20:35:23.263
3,5,1,7.0,NaN,2010-07-20 19:18:01.250,47,9920.0,<p>I have read a few proofs that $\sqrt{2}$ is...,38.0,327363.0,user242,2016-04-21 15:23:49.687,2017-10-05 05:19:19.183,How can you prove that the square root of two ...,<elementary-number-theory><proof-writing><radi...,12.0,7,17.0,NaT,NaT
4,6,1,281.0,NaN,2010-07-20 19:20:00.543,40,3814.0,"<p>I'm looking for a nice, quick online graphi...",41.0,39567.0,user126,2012-09-14 14:39:21.250,2018-08-07 11:15:52.563,What is your favorite online graphing tool?,<soft-question><math-software>,7.0,0,29.0,NaT,2010-07-20 19:20:00.543
5,7,2,NaN,5.0,2010-07-20 19:21:52.240,71,NaN,<p>You use a proof by contradiction. Basically...,45.0,NaN,None,NaT,2010-07-20 19:21:52.240,None,None,NaN,11,NaN,NaT,NaT
6,8,1,17.0,NaN,2010-07-20 19:22:12.190,33,1531.0,"<p>I was reading up on the Fibonacci Sequence,...",40.0,514496.0,user126,2018-01-24 04:10:51.457,2018-01-24 04:10:51.457,How are we able to calculate specific numbers ...,<linear-algebra><combinatorics><generating-fun...,7.0,0,3.0,NaT,NaT
7,9,2,NaN,1.0,2010-07-20 19:22:20.193,155,NaN,<p>Suppose no one ever taught you the names fo...,8.0,8.0,None,2017-04-16 13:29:54.037,2017-04-16 13:29:54.037,None,None,NaN,7,NaN,NaT,NaT
8,11,1,49.0,NaN,2010-07-20 19:23:09.117,245,38092.0,<p>I'm told by <em>smart people</em> that\n$$0...,41.0,137739.0,None,2018-05-30 21:40:23.323,2018-05-31 17:00:13.053,Is it true that $0.999999999\dots=1$?,<real-analysis><algebra-precalculus><decimal-e...,22.0,14,113.0,NaT,2010-07-28 06:53:43.987
9,13,2,NaN,1.0,2010-07-20 19:23:17.570,6,NaN,<p>The basic concept is thus:</p>\n\n<ul>\n<li...,35.0,NaN,None,NaT,2010-07-20 19:23:17.570,None,None,NaN,0,NaN,NaT,NaT
10,53,2,NaN,22.0,2010-07-20 19:40:39.277,4,NaN,<p>Assuming you know the definition of orthogo...,16.0,NaN,None,NaT,2010-07-20 19:40:39.277,None,None,NaN,0,NaN,NaT,NaT
11,905,2,NaN,29.0,2010-07-28 03:39:45.887,6,NaN,<p>Try sage. It's like python (it is actually...,326.0,NaN,None,NaT,2010-07-28 03:39:45.887,None,None,NaN,0,NaN,NaT,2010-07-28 03:39:45.887
12,14,2,NaN,1.0,2010-07-20 19:23:20.317,-2,NaN,<p>Just simple intuitive explanation.</p>\n\n<...,33.0,33.0,None,2015-11-28 13:08:59.957,2015-11-28 13:08:59.957,None,None,NaN,6,NaN,NaT,NaT
13,15,2,NaN,6.0,2010-07-20 19:23:21.220,18,NaN,"<p>Well, I am not sure where you want to embed...",16.0,41.0,None,2010-07-20 19:26:37.047,2010-07-20 19:26:37.047,None,None,NaN,0,NaN,NaT,2010-07-20 19:23:21.220
14,16,2,NaN,5.0,2010-07-20 19:23:50.563,22,NaN,<p>Consider this proof by contradiction:</p>\n...,48.0,NaN,None,NaT,2010-07-20 19:23:50.563,None,None,NaN,1,NaN,NaT,NaT
15,17,2,NaN,8.0,2010-07-20 19:23:54.230,22,NaN,<p>Wikipedia has a closed-form function called...,38.0,38.0,None,2010-07-22 18:38:42.820,2010-07-22 18:38:42.820,None,None,NaN,5,NaN,NaT,NaT
16,18,1,93.0,NaN,2010-07-20 19:24:34.823,7,2305.0,<p>Given the semi-major axis and a flattening ...,17.0,343408.0,None,2017-03-02 13:36:40.420,2017-03-02 13:36:40.420,How do you calculate the semi-minor axis of an...,<geometry>,2.0,7,2.0,NaT,NaT
17,20,1,40.0,NaN,2010-07-20 19:25:09.563,15,4748.0,"<p>In mathematics, there seem to be a lot of d...",54.0,465225.0,user126,2017-08-02 15:54:22.223,2017-08-02 15:54:22.223,"What is a real number (also rational, decimal,...",<terminology><definition><number-systems>,10.0,8,8.0,NaT,NaT
18,22,1,53.0,NaN,2010-07-20 19:25:58.483,13,1467.0,"<p>By matrix-defined, I mean</p>\n\n<p>$$\left...",51.0,167548.0,user126,2016-12-23 23:48:03.357,2016-12-23 23:48:03.357,Why is the matrix-defined Cross Product of two...,<linear-algebra><matrices><inner-product-space...,4.0,0,NaN,NaT,NaT
19,24,2,NaN,8.0,2010-07-20 19:26:16.643,5,NaN,<p>The closed form calculation for Fibonacci s...,53.0,NaN,None,NaT,2010-07-20 19:26:16.643,None,None,NaN,0,NaN,NaT,NaT
20,26,2,NaN,8.0,2010-07-20 19:26:38.187,4,NaN,"<p>You can use Binet's formula, described at <...",55.0,NaN,None,NaT,2010-07-20 19:26:38.187,None,None,NaN,0,NaN,NaT,NaT
21,29,1,1572.0,NaN,2010-07-20 19:27:09.700,34,2301.0,<p>I'm looking for an online or software calcu...,54.0,73.0,None,2010-07-28 01:04:25.440,2018-08-26 16:40:25.617,Can you recommend a decent online or software ...,<soft-question><big-list><math-software><compu...,23.0,1,16.0,NaT,2010-07-28 01:32:30.370
22,30,2,NaN,11.0,2010-07-20 19:27:38.963,11,NaN,<p>Given (by long division):<br>\n$\frac{1}{3}...,38.0,38.0,None,2011-02-21 02:52:26.000,2011-02-21 02:52:26.000,None,None,NaN,2,NaN,NaT,2010-07-28 06:53:43.987
23,31,2,NaN,11.0,2010-07-20 19:27:39.433,13,NaN,<p>Indeed this is true. The underlying reason ...,56.0,78482.0,None,2017-02-24 20:51:30.207,2017-02-24 20:51:30.207,None,None,NaN,16,NaN,NaT,2010-07-28 06:53:43.987
24,35,2,NaN,1.0,2010-07-20 19:29:54.777,15,NaN,"<p><a href=""http://en.wikipedia.org/wiki/Hilbe...",49.0,NaN,None,NaT,2010-07-20 19:29:54.777,None,None,NaN,2,NaN,NaT,NaT
25,38,2,NaN,29.0,2010-07-20 19:30:50.313,7,NaN,"<p>Lots of people like to use <a href=""http://...",45.0,NaN,None,NaT,2010-07-20 19:30:50.313,None,None,NaN,0,NaN,NaT,2010-07-28 01:32:30.370
26,66,2,NaN,57.0,2010-07-20 19:49:03.750,4,NaN,<p>There are several important kinds of relati...,8.0,NaN,None,NaT,2010-07-20 19:49:03.750,None,None,NaN,1,NaN,NaT,NaT
27,40,2,NaN,20.0,2010-07-20 19:32:21.590,12,NaN,"<ul>\n<li><p>Natural numbers<br>\nThe ""countin...",38.0,38.0,None,2010-07-20 19:37:58.457,2010-07-20 19:37:58.457,None,None,NaN,16,NaN,NaT,NaT
28,41,2,NaN,11.0,2010-07-20 19:32:44.553,23,NaN,<p><code>.999... = 1</code> because <code>.99...,19.0,19.0,None,2010-07-23 02:13:49.417,2010-07-23 02:13:49.417,None,None,NaN,0,NaN,NaT,2010-07-28 06:53:43.987
29,42,2,NaN,22.0,2010-07-20 19:33:50.870,-2,NaN,"<p>The obvious but slightly trite answer is ""b...",56.0,232040.0,None,2015-08-21 15:44:32.773,2015-08-21 15:44:32.773,None,None,NaN,7,NaN,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372518,2902322,2,NaN,2901041.0,2018-09-02 03:51:13.333,0,NaN,<p>Instead of trying to eliminate the negation...,256001.0,NaN,None,NaT,2018-09-02 03:51:13.333,None,None,NaN,0,NaN,NaT,NaT
2372519,2902323,2,NaN,2902307.0,2018-09-02 03:55:38.997,0,NaN,<p>Summing up each row (or column) of a matrix...,35983.0,35983.0,None,2018-09-02 04:10:17.827,2018-09-02 04:10:17.827,None,None,NaN,9,NaN,NaT,NaT
2372520,2902325,1,NaN,NaN,2018-09-02 03:59:22.750,0,19.0,<p>How to show that if an $m$ by $n$ matrix ha...,426645.0,NaN,None,NaT,2018-09-02 04:08:49.320,How to show that if an $m$ by $n$ matrix has t...,<linear-algebra>,1.0,1,1.0,NaT,NaT
2372521,2902328,2,NaN,2900424.0,2018-09-02 04:03:01.077,0,NaN,"<p>In both, use the following formula, availab...",321120.0,NaN,None,NaT,2018-09-02 04:03:01.077,None,None,NaN,0,NaN,NaT,NaT
2372522,2902329,2,NaN,2902264.0,2018-09-02 04:03:31.627,1,NaN,<p>Your proof is correct and detailed.<br>\nIm...,524154.0,NaN,None,NaT,2018-09-02 04:03:31.627,None,None,NaN,0,NaN,NaT,NaT
2372523,2902330,1,NaN,NaN,2018-09-02 04:05:51.273,0,17.0,<p>Is the following map a quotient map?\n$$f:G...,373817.0,373817.0,None,2018-09-02 04:11:51.753,2018-09-02 04:11:51.753,Quotient map from $GL_2(\Bbb R)$,<general-topology>,0.0,1,NaN,NaT,NaT
2372524,2902331,2,NaN,2902253.0,2018-09-02 04:06:18.163,0,NaN,<p>We discussed this type of integrals <a href...,108128.0,NaN,None,NaT,2018-09-02 04:06:18.163,None,None,NaN,0,NaN,NaT,NaT
2372525,2902332,2,NaN,2902318.0,2018-09-02 04:08:38.660,5,NaN,"<p>Your sequence $1,2,4,5,7,8,\dots$ satisfies...",111012.0,NaN,None,NaT,2018-09-02 04:08:38.660,None,None,NaN,4,NaN,NaT,NaT
2372526,2902333,2,NaN,2902325.0,2018-09-02 04:08:49.320,1,NaN,<p>Hint: recall that a matrix $A \in \mathbb{k...,362866.0,NaN,None,NaT,2018-09-02 04:08:49.320,None,None,NaN,0,NaN,NaT,NaT
2372527,2902334,2,NaN,211762.0,2018-09-02 04:09:06.217,0,NaN,<p>This is an answer based on the comment give...,224467.0,NaN,None,NaT,2018-09-02 04:09:06.217,None,None,NaN,0,NaN,NaT,NaT
2372528,2902335,1,NaN,NaN,2018-09-02 04:13:43.927,1,9.0,<p>What is the expected number of rolls to get...,589141.0,NaN,None,NaT,2018-09-02 04:13:43.927,Expected value of number of rolls and sum valu...,<probability><probability-theory><dice><expect...,0.0,0,NaN,NaT,NaT
2372529,2902336,1,NaN,NaN,2018-09-02 04:14:10.037,1,20.0,<blockquote>\n <p>If the rectangle hyperbola ...,372201.0,248286.0,None,2018-09-02 04:30:18.453,2018-09-02 04:30:18.453,"Value of $g,f$ in a circle",<conic-sections>,0.0,2,1.0,NaT,NaT
2372530,2902345,2,NaN,2902295.0,2018-09-02 04:31:45.707,0,NaN,<p>$a_n = n^{1/n}\n$\nand\n$b_n = \frac{a_{n+1...,13079.0,NaN,None,NaT,2018-09-02 04:31:45.707,None,None,NaN,0,NaN,NaT,NaT
2372531,2902337,2,NaN,100448.0,2018-09-02 04:15:30.187,1,NaN,<h1>An Alternative to Circles</h1>\n\n<p>Since...,589126.0,NaN,None,NaT,2018-09-02 04:15:30.187,None,None,NaN,0,NaN,NaT,NaT
2372532,2902338,2,NaN,2902318.0,2018-09-02 04:16:01.837,2,NaN,<p>If you consider\n$$a_k=1+3k\qquad b_k=2+3k$...,82404.0,NaN,None,NaT,2018-09-02 04:16:01.837,None,None,NaN,0,NaN,NaT,NaT
2372533,2902339,1,NaN,NaN,2018-09-02 04:16:27.987,0,7.0,"<p>Give problem data $(A, b)$ where $A$ is an ...",4460.0,NaN,None,NaT,2018-09-02 04:16:27.987,Equivalence of Parameterizations of Least Squa...,<linear-algebra>,0.0,1,NaN,NaT,NaT
2372534,2902340,1,NaN,NaN,2018-09-02 04:17:12.760,1,20.0,<p>When only three types of bit strings <code>...,589143.0,579780.0,None,2018-09-02 04:26:26.493,2018-09-02 04:32:02.903,Combinatorics problem with bit-strings,<combinatorics><discrete-mathematics><combinat...,1.0,0,NaN,NaT,NaT
2372535,2902341,2,NaN,2902212.0,2018-09-02 04:21:41.160,0,NaN,<p>Let $f(x) = \max_k l_k(x)$. Note that $f(0)...,27978.0,NaN,None,NaT,2018-09-02 04:21:41.160,None,None,NaN,0,NaN,NaT,NaT
2372536,2902342,2,NaN,2902297.0,2018-09-02 04:22:02.653,1,NaN,<p>No. You have to go to more than a binary ra...,397125.0,NaN,None,NaT,2018-09-02 04:22:02.653,None,None,NaN,0,NaN,NaT,NaT
2372537,2902343,2,NaN,2159062.0,2018-09-02 04:25:23.733,1,NaN,"<p>$$ \n\cos^2{x}+(1-a)\cos{x}-a^2\,\lt0 \quad...",367051.0,367051.0,None,2018-09-02 04:40:27.830,2018-09-02 04:40:27.830,None,None,NaN,0,NaN,NaT,NaT
2372538,2902344,1,NaN,NaN,2018-09-02 04:28:36.797,0,12.0,<p>The following question came up on a recent ...,501024.0,NaN,None,NaT,2018-09-02 04:28:36.797,"Proof Verification: Show that $R = I + J$, whe...",<proof-verification><ring-theory>,0.0,0,NaN,NaT,NaT
2372539,2902346,2,NaN,2902340.0,2018-09-02 04:32:02.903,2,NaN,"<p>The available strings form whats called a ""...",360795.0,NaN,None,NaT,2018-09-02 04:32:02.903,None,None,NaN,0,NaN,NaT,NaT
2372540,2902347,1,NaN,NaN,2018-09-02 04:35:46.533,-2,23.0,"<p>Two even functions, say f(x) and g(x), when...",586799.0,291201.0,None,2018-09-02 04:45:22.297,2018-09-02 04:46:01.230,Is the product of two even functions even or odd?,<functions>,1.0,4,NaN,NaT,NaT
2372541,2902348,2,NaN,2902347.0,2018-09-02 04:39:07.853,6,NaN,<p>Product of two even functions is even.</p>\...,439587.0,439587.0,None,2018-09-02 04:46:01.230,2018-09-02 04:46:01.230,None,None,NaN,1,NaN,NaT,NaT
2372542,2902349,1,NaN,NaN,2018-09-02 04:46:46.200,0,7.0,"<p>I need to prove only one way, </p>\n\n<p>I ...",589140.0,NaN,None,NaT,2018-09-02 04:46:46.200,"Proof of: $m = n = 0 \iff m + n =0$ $n,m \in N$",<proof-verification><summation>,0.0,0,NaN,NaT,NaT
2372543,2902350,1,NaN,NaN,2018-09-02 04:48:55.523,0,5.0,"<p>For all $x,y&gt;0$, $$\frac{1}{(x+1)^2} + \...",269497.0,NaN,None,NaT,2018-09-02 04:48:55.523,Prove this inequality for given conditions,<algebra-precalculus><inequality><a.m.-g.m.-in...,0.0,0,NaN,NaT,NaT
2372544,2902351,1,NaN,NaN,2018-09-02 04:49:09.833,0,7.0,"<p>Usually, in mathematics, diagrams appear to...",491226.0,NaN,None,NaT,2018-09-02 04:49:09.833,What are some examples of fascinatingly comple...,<intuition><big-list>,0.0,0,NaN,NaT,NaT
2372545,2902352,1,NaN,NaN,2018-09-02 04:53:35.857,0,5.0,<p>Suppose we want to estimate $\pi$. We adopt...,136523.0,NaN,None,NaT,2018-09-02 04:53:35.857,Can we find an unbiased estimator of $\pi$?,<probability-distributions><random-variables><...,0.0,0,NaN,NaT,NaT
2372546,2902353,1,NaN,NaN,2018-09-02 04:55:59.747,0,7.0,<p>I am taking an undergraduate analysis cours...,589146.0,NaN,None,NaT,2018-09-02 04:55:59.747,What does it mean for a set to be open inside ...,<real-analysis><general-topology><analysis>,0.0,0,NaN,NaT,NaT
2372547,2902354,2,NaN,2901246.0,2018-09-02 04:56:36.770,0,NaN,<p>For your first conjecture:</p>\n\n<p>Write<...,13079.0,NaN,None,NaT,2018-09-02 04:56:36.770,None,None,NaN,0,NaN,NaT,NaT

In [57]:
# df_posts.set_index('id', inplace=True)

In [150]:
questions = merged_year_posts[merged_year_posts['posttypeid'] == 1]

In [151]:
questions

,posttypeid,acceptedanswerid,parentid,creationdate,score,viewcount,body,owneruserid,lasteditoruserid,lasteditordisplayname,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,upvotes
id,,,,,,,,,,,,,,,,,,,,,
1,1,9.0,NaN,2010-07-20 19:09:27.200,136,7391.0,<p>Can someone explain to me how there can be ...,10.0,32803.0,user126,...,19,4,10,23,22,12,14,20,9,133
3,1,NaN,NaN,2010-07-20 19:12:14.353,99,57921.0,"<p><a href=""http://mathfactor.uark.edu/"">mathf...",29.0,498.0,user126,...,7,5,6,11,16,8,14,23,5,95
5,1,7.0,NaN,2010-07-20 19:18:01.250,47,9920.0,<p>I have read a few proofs that $\sqrt{2}$ is...,38.0,327363.0,user242,...,9,5,4,6,8,3,5,7,3,50
6,1,281.0,NaN,2010-07-20 19:20:00.543,40,3814.0,"<p>I'm looking for a nice, quick online graphi...",41.0,39567.0,user126,...,5,6,7,5,5,2,3,5,3,41
8,1,17.0,NaN,2010-07-20 19:22:12.190,33,1531.0,"<p>I was reading up on the Fibonacci Sequence,...",40.0,514496.0,user126,...,6,4,3,7,1,3,1,4,4,33
11,1,49.0,NaN,2010-07-20 19:23:09.117,245,38092.0,<p>I'm told by <em>smart people</em> that\n$$0...,41.0,137739.0,None,...,14,0,0,0,58,66,57,43,20,258
18,1,93.0,NaN,2010-07-20 19:24:34.823,7,2305.0,<p>Given the semi-major axis and a flattening ...,17.0,343408.0,None,...,2,1,0,1,1,1,0,4,0,10
20,1,40.0,NaN,2010-07-20 19:25:09.563,15,4748.0,"<p>In mathematics, there seem to be a lot of d...",54.0,465225.0,user126,...,5,2,1,2,1,2,2,5,0,20
22,1,53.0,NaN,2010-07-20 19:25:58.483,13,1467.0,"<p>By matrix-defined, I mean</p>\n\n<p>$$\left...",51.0,167548.0,user126,...,6,0,0,2,1,0,1,2,1,13
29,1,1572.0,NaN,2010-07-20 19:27:09.700,34,2301.0,<p>I'm looking for an online or software calcu...,54.0,73.0,None,...,10,1,8,3,3,1,1,5,2,34
51,1,109.0,NaN,2010-07-20 19:39:11.557,14,2671.0,<p>What length of rope should be used to tie a...,59.0,NaN,user126,...,5,0,1,3,2,0,1,2,0,14
56,1,NaN,NaN,2010-07-20 19:41:55.687,23,3395.0,"<p>As I've understood it, what I've learned is...",63.0,267844.0,user126,...,6,2,3,2,4,5,0,2,1,25
57,1,134.0,NaN,2010-07-20 19:42:33.500,10,4730.0,<p>This is simply not clicking for me. I'm cur...,44.0,280290.0,None,...,3,1,0,1,3,1,0,2,0,11
58,1,70.0,NaN,2010-07-20 19:43:20.457,40,8153.0,<p>I recently discovered Benford's Law. I find...,5.0,73.0,None,...,7,6,2,9,5,4,5,2,1,41
59,1,65.0,NaN,2010-07-20 19:43:30.097,7,4793.0,"<p>Given two points around an origin $(0,0)$ i...",24.0,230715.0,user126,...,2,1,0,1,2,0,0,1,0,7
67,1,72.0,NaN,2010-07-20 19:49:29.490,37,2338.0,<p>I hear a lot about Elliptic Curve Cryptogra...,48.0,467.0,None,...,16,4,2,1,4,2,2,3,3,37
71,1,78.0,NaN,2010-07-20 19:52:14.927,31,12403.0,<p>I've recently started reading about Quatern...,34.0,73.0,None,...,7,2,1,3,2,5,2,7,2,31
74,1,1273.0,NaN,2010-07-20 19:54:33.893,7,1229.0,<p>Let's say I know $X$ is a Gaussian Variable...,33.0,49437.0,None,...,2,1,0,0,1,2,0,0,1,7
75,1,80.0,NaN,2010-07-20 19:55:05.293,75,49962.0,"<p>Rings, groups, and fields all feel similar....",37.0,52938.0,None,...,4,2,1,3,4,12,13,23,8,70
77,1,85.0,NaN,2010-07-20 19:57:06.617,39,25192.0,<p>What purposes do the Dot and Cross products...,24.0,NaN,user126,...,10,3,4,3,5,4,2,6,2,39
81,1,NaN,NaN,2010-07-20 20:01:55.013,161,53461.0,<p>I have the one or other interesting Math bl...,79.0,2109.0,None,...,11,22,12,15,28,20,20,19,12,159
83,1,88.0,NaN,2010-07-20 20:04:20.733,62,3795.0,<p>I'm talking in the range of 10-12 years old...,24.0,100.0,None,...,25,10,5,10,1,5,4,3,0,63
196,1,229.0,NaN,2010-07-20 23:50:41.403,30,6883.0,<p>I keep looking at this picture and its driv...,104.0,NaN,user126,...,6,4,6,2,5,3,1,3,1,31
90,1,NaN,NaN,2010-07-20 20:11:37.703,41,6364.0,"<p>Not sure if this is the place for it, but t...",34.0,498.0,None,...,11,9,2,4,4,4,3,5,0,42
97,1,1224.0,NaN,2010-07-20 20:20:22.223,15,12051.0,<p>I am looking for an accurate algorithm to c...,92.0,11667.0,None,...,2,1,1,0,4,0,3,4,0,15
98,1,106.0,NaN,2010-07-20 20:21:33.407,14,887.0,<p>I am looking for a reference (book or artic...,76.0,82255.0,None,...,7,1,3,0,1,1,0,1,0,14
101,1,105.0,NaN,2010-07-20 20:30:39.280,4,273.0,<p>This is in relation to the Euler Problem $...,44.0,NaN,user63181,...,2,0,0,0,1,0,0,1,0,4
107,1,1159.0,NaN,2010-07-20 20:38:57.700,47,5358.0,"<p>It is $10$ o'clock, and I have a box. </p>...",73.0,53464.0,None,...,7,9,8,10,2,4,3,1,2,46
112,1,115.0,NaN,2010-07-20 20:51:07.517,8,726.0,<p>I keep seeing this symbol $\nabla$ around a...,82.0,269041.0,None,...,4,0,0,2,1,0,0,0,1,8
113,1,130.0,NaN,2010-07-20 20:56:33.853,18,6807.0,"<p>If you know it, also try to include the pre...",66.0,498.0,user126,...,3,2,1,7,2,0,2,1,1,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2805939,1,2805945.0,NaN,2018-06-02 22:09:52.493,1,27.0,<blockquote>\n <p>Suppose we are given two ar...,389088.0,NaN,None,...,0,0,0,0,0,0,0,0,1,1
2805941,1,2805967.0,NaN,2018-06-02 22:12:37.227,3,61.0,<p>Let $U\subset \mathbb R^m$ be an open set a...,491866.0,NaN,None,...,0,0,0,0,0,0,0,0,3,3
2805949,1,NaN,NaN,2018-06-02 22:28:53.807,1,36.0,<p>I need to find the maximum value of the fol...,165639.0,NaN,None,...,0,0,0,0,0,0,0,0,1,1
2805955,1,2805971.0,NaN,2018-06-02 22:41:08.063,1,32.0,<p>This PDF gives the following definition of ...,166180.0,70857.0,None,...,0,0,0,0,0,0,0,0,1,1
2805956,1,2828817.0,NaN,2018-06-02 22:42:00.127,1,51.0,<p>I have a touch sensor with 28 pixels that o...,250265.0,4280.0,None,...,0,0,0,0,0,0,0,0,1,1
2805958,1,2805966.0,NaN,2018-06-02 22:44:51.743,1,43.0,<p>I'm confused about the proof of a simple co...,35203.0,11667.0,None,...,0,0,0,0,0,0,0,0,1,1
2805976,1,NaN,NaN,2018-06-02 23:07:19.387,1,27.0,<p>I'd just be interested if there is a source...,441469.0,NaN,None,...,0,0,0,0,0,0,0,0,1,1
2805979,1,2806294.0,NaN,2018-06-02 23:10:26.607,3,49.0,<p><strong>The Question:</strong></p>\n\n<p>(i...,520107.0,NaN,None,...,0,0,0,0,0,0,0,0,1,1
2805982,1,NaN,NaN,2018-06-02 23:13:33.997,1,51.0,<p>Consider the “ special function “</p>\n\n<p...,39261.0,NaN,None,...,0,0,0,0,0,0,0,0,1,1
2805985,1,2806042.0,NaN,2018-06-02 23:20:22.087,2,73.0,<p><strong>The Problem:</strong></p>\n\n<p>Sup...,197045.0,11667.0,None,...,0,0,0,0,0,0,0,0,2,2
2805998,1,2806008.0,NaN,2018-06-02 23:46:46.573,1,25.0,"<p>I am reading a representation theory book, ...",138119.0,138119.0,None,...,0,0,0,0,0,0,0,0,1,1
2806006,1,2806021.0,NaN,2018-06-02 23:56:27.607,1,46.0,"<p>Let $m,n$ be two natural numbers, $a,b$ are...",378203.0,378203.0,None,...,0,0,0,0,0,0,0,0,1,1
2806007,1,2806046.0,NaN,2018-06-02 23:58:20.243,4,36.0,<p>Let $X$ be a continuous random variable wit...,225419.0,11667.0,None,...,0,0,0,0,0,0,0,0,4,4
2806010,1,NaN,NaN,2018-06-03 00:02:18.317,1,40.0,<p>Here $\lambda \in \mathbb{C}$ and $$a_n = \...,432563.0,11667.0,None,...,0,0,0,0,0,0,0,0,1,1
2806036,1,2807820.0,NaN,2018-06-03 00:55:19.983,3,99.0,<p>This is a very general question. I am wond...,172599.0,NaN,None,...,0,0,0,0,0,0,0,0,1,1
2806012,1,2806033.0,NaN,2018-06-03 00:06:30.107,0,38.0,<p>I don't know how to do the change of variab...,566464.0,118056.0,None,...,0,0,0,0,0,0,0,0,1,1
2806026,1,2806029.0,NaN,2018-06-03 00:45:06.847,1,31.0,"<p>For what positive integers a, b, c, and d, ...",566757.0,350060.0,None,...,0,0,0,0,0,0,0,0,1,1
2806034,1,2806040.0,NaN,2018-06-03 00:54:12.600,2,116.0,"<p>How to solve this summation ? Also, I'm not...",111711.0,480423.0,None,...,0,0,0,0,0,0,0,0,3,3
2806041,1,NaN,NaN,2018-06-03 01:05:53.317,1,35.0,<p>I'm trying to reduce the general tensor exp...,550792.0,NaN,None,...,0,0,0,0,0,0,0,0,1,1
2806050,1,2806114.0,NaN,2018-06-03 01:20:34.993,3,176.0,"<p>The problem is prove that a connected, comp...",310078.0,480423.0,None,...,0,0,0,0,0,0,0,0,1,1
2806060,1,NaN,NaN,2018-06-03 01:49:41.623,1,49.0,<p>I know that it is not possible to tie two k...,531648.0,531648.0,None,...,0,0,0,0,0,0,0,0,1,1
2806072,1,NaN,NaN,2018-06-03 02:20:01.477,1,40.0,<p>I know that $AB$ and $BA$ have the same non...,545139.0,545139.0,None,...,0,0,0,0,0,0,0,0,2,2
2806079,1,NaN,NaN,2018-06-03 02:35:31.777,3,190.0,"<p>The alternating series, $s_n=\sum_{i=2}^{n}...",287362.0,287362.0,None,...,0,0,0,0,0,0,0,0,3,3
2806095,1,2806097.0,NaN,2018-06-03 03:01:43.070,1,46.0,"<p>In the proof, Rudin defines $g(t) = f(t) - ...",356954.0,NaN,None,...,0,0,0,0,0,0,0,0,1,1
2806100,1,2806369.0,NaN,2018-06-03 03:09:51.923,1,112.0,<blockquote>\n <p>What are the minimum and ma...,476382.0,339790.0,None,...,0,0,0,0,0,0,0,0,2,2
2806103,1,NaN,NaN,2018-06-03 03:14:36.117,1,86.0,<p>I'd like to have the following proof verifi...,555729.0,9003.0,None,...,0,0,0,0,0,0,0,0,1,1
2806111,1,2806129.0,NaN,2018-06-03 03:59:08.550,1,22.0,<p>A friend and I were working on a Calculus (...,566970.0,NaN,None,...,0,0,0,0,0,0,0,0,1,1
2806123,1,2806127.0,NaN,2018-06-03 04:17:17.783,1,23.0,<p>I have a basic topology question. Let's say...,294517.0,NaN,None,...,0,0,0,0,0,0,0,0,1,1
2806133,1,2806138.0,NaN,2018-06-03 04:29:29.510,1,44.0,"<blockquote>\n <p>For an $n \times n$ matrix,...",506965.0,NaN,None,...,0,0,0,0,0,0,0,0,1,1
2806135,1,NaN,NaN,2018-06-03 04:31:38.913,2,59.0,<p>I'm being asked to prove the following gene...,554300.0,NaN,None,...,0,0,0,0,0,0,0,0,1,1

In [152]:
questions.shape

(671683, 29)

In [153]:
linear_algebra = questions[questions.tags.str.contains("linear-algebra") & questions.tags.notnull()]

In [154]:
linear_algebra.columns

Index([           'posttypeid',      'acceptedanswerid',
                    'parentid',          'creationdate',
                       'score',             'viewcount',
                        'body',           'owneruserid',
            'lasteditoruserid', 'lasteditordisplayname',
                'lasteditdate',      'lastactivitydate',
                       'title',                  'tags',
                 'answercount',          'commentcount',
               'favoritecount',            'closeddate',
          'communityowneddate',                    2010,
                          2011,                    2012,
                          2013,                    2014,
                          2015,                    2016,
                          2017,                    2018,
                     'upvotes'],
      dtype='object')

In [155]:
linear_algebra[[2010, 2011, 2012 , 2013, 2014, 2015, 2016, 2017, 2018, 'upvotes','tags', 'score', 'title']]

,2010,2011,2012,2013,2014,2015,2016,2017,2018,upvotes,tags,score,title
id,,,,,,,,,,,,,
8,6,4,3,7,1,3,1,4,4,33,<linear-algebra><combinatorics><generating-fun...,33,How are we able to calculate specific numbers ...
22,6,0,0,2,1,0,1,2,1,13,<linear-algebra><matrices><inner-product-space...,13,Why is the matrix-defined Cross Product of two...
56,6,2,3,2,4,5,0,2,1,25,<linear-algebra><vector-spaces><inner-product-...,23,What Is An Inner Product Space?
59,2,1,0,1,2,0,0,1,0,7,<linear-algebra><geometry>,7,Calculating an Angle from $2$ points in space
71,7,2,1,3,2,5,2,7,2,31,<soft-question><big-list><linear-algebra><appl...,31,Real world uses of Quaternions?
77,10,3,4,3,5,4,2,6,2,39,<linear-algebra>,39,Understanding Dot and Cross Product
185,1,0,0,2,1,0,0,0,0,4,<linear-algebra><vector-spaces>,3,Recasting points from one vector space to another
336,6,1,3,3,6,5,3,3,3,33,<linear-algebra><matrices><geometry>,34,Why are $3D$ transformation matrices $4 \times...
423,4,0,1,0,1,2,2,3,2,15,<calculus><linear-algebra>,15,Intuitive reasoning behind the Chain Rule in m...
450,3,0,1,1,2,1,3,1,2,14,<linear-algebra><transformation>,15,Can non-linear transformations be represented ...
524,2,1,0,0,3,0,0,0,0,6,<linear-algebra><numerical-methods><numerical-...,5,How can I tell which matrix decomposition to u...
595,3,2,1,0,1,2,4,0,1,14,<linear-algebra><matrices>,14,What is the most efficient way to determine if...
624,7,1,2,3,0,5,3,4,1,26,<linear-algebra><systems-of-equations><chemistry>,26,Balance chemical equations without trial and e...
668,25,42,42,53,64,92,91,87,38,534,<linear-algebra><matrices><determinant><intuit...,549,What's an intuitive way to think about the det...
697,5,0,1,0,0,0,0,0,1,7,<linear-algebra><big-list><approximation><regr...,7,Are there variations on least-squares approxim...
713,7,1,0,2,1,0,2,3,0,16,<geometry><linear-algebra><intuition><tensors>,16,How to visualize a rank-2 tensor?
741,3,2,0,1,0,1,0,0,1,8,<linear-algebra><algorithms><computer-science>...,9,What is linear programming?
750,4,0,0,0,0,0,0,1,0,5,<linear-algebra><geometry><determinant>,5,Determinants and volume of parallelotopes
872,2,0,3,0,0,0,1,0,0,6,<linear-algebra><exterior-algebra>,7,What is the relationship between the Hodge dua...
978,0,3,0,6,4,4,4,8,4,33,<linear-algebra><matrices><inequality><matrix-...,36,How to prove and interpret $\operatorname{rank...
996,0,0,1,0,2,0,0,0,2,5,<linear-algebra>,5,What is the difference between matrix theory a...
1091,5,2,1,2,0,0,0,0,0,10,<linear-algebra><eigenvalues-eigenvectors><int...,10,Is there a geometrical interpretation to the n...
1271,0,1,1,1,0,0,0,0,0,3,<linear-algebra><number-theory>,3,Solving systems of equations in roots of unity
1337,3,1,1,0,1,0,0,1,0,7,<geometry><linear-algebra>,6,Dot product in coordinates
1618,8,1,1,0,0,0,0,0,0,10,<linear-algebra><real-analysis><functional-ana...,10,Is the natural map $L^p(X) \otimes L^p(Y) \to ...
1822,5,1,3,2,2,0,0,0,0,13,<linear-algebra>,12,Is reducing a matrix to row echelon form usefu...
1829,2,0,0,0,3,0,0,0,0,5,<linear-algebra><examples-counterexamples>,5,Tips for writing math solutions for others
1872,4,0,1,0,0,0,1,0,0,6,<linear-algebra><quaternions><matrices>,6,On multiplying quaternion matrices
1873,1,1,0,0,0,0,0,1,0,3,<linear-algebra><eigenvalues-eigenvectors>,2,process of finding eigenvalues and eigenvectors
1884,0,0,0,0,0,0,0,1,0,1,<linear-algebra>,1,How to find eigenvectors/eigenvalues of a matr...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2804657,0,0,0,0,0,0,0,0,1,1,<linear-algebra><eigenvalues-eigenvectors>,0,Simple Eigenspace Calculation
2804728,0,0,0,0,0,0,0,0,1,1,<linear-algebra><group-theory><representation-...,1,How can the external tensor product of irreduc...
2804844,0,0,0,0,0,0,0,0,1,1,<linear-algebra><integer-lattices>,1,Why does the set of integer vectors in the nul...
2804940,0,0,0,0,0,0,0,0,1,1,<linear-algebra>,0,arrangement of basis
2804993,0,0,0,0,0,0,0,0,1,1,<convergence><numerical-linear-algebra><matrix...,1,Multiplicative update rules for NMF
2805022,0,0,0,0,0,0,0,0,1,1,<linear-algebra><linear-transformations>,1,$V = \operatorname{Im} T \oplus \operatorname{...
2805118,0,0,0,0,0,0,0,0,1,1,<linear-algebra><matrices><polynomials>,0,Properties of Matrix Polynomials
2805147,0,0,0,0,0,0,0,0,2,2,<linear-algebra><differential-geometry><homolo...,2,"For genus $g$ Riemann surface, $\operatorname{..."
2805149,0,0,0,0,0,0,0,0,1,1,<linear-algebra><matrices><proof-verification>...,1,Statement about Generalised Eigenvectors Invol...
2805249,0,0,0,0,0,0,0,0,3,3,<linear-algebra><matrices><jordan-normal-form>,3,Finding a Jordan basis of a $3\times 3$ matrix
2805256,0,0,0,0,0,0,0,0,1,1,<linear-algebra>,1,Calculating Dimension of Intersection of Kernels
2805261,0,0,0,0,0,0,0,0,1,1,<linear-algebra><optimization><eigenvalues-eig...,1,Show That Minimizer of Rayleigh Quotient Is th...
2805262,0,0,0,0,0,0,0,0,3,3,<linear-algebra><optimization><convex-optimiza...,4,Show that $(A^TA)^{-1} A^T$ minimizes $\mbox{T...
2805291,0,0,0,0,0,0,0,0,1,1,<linear-algebra><matrices><diagonalization><qu...,1,Confusion about orthogonal basis of a quadrati...
2805325,0,0,0,0,0,0,0,0,1,1,<linear-algebra><abstract-algebra><matrices><m...,5,Smiths normal form is similar to $xI-A.$
2805387,0,0,0,0,0,0,0,0,1,1,<linear-algebra><functional-analysis><linear-t...,1,"Is $T$ surjective,injective or both."
2805404,0,0,0,0,0,0,0,0,2,2,<linear-algebra><diagonalization><minimal-poly...,2,Does this fact about the minimal polynomial gi...
2805429,0,0,0,0,0,0,0,0,2,2,<linear-algebra><matrices><positive-definite><...,2,Diagonal elements of a symmetric matrix and po...
2805461,0,0,0,0,0,0,0,0,1,1,<linear-algebra><algorithms><computational-com...,5,Fast arbitrary decomposition of a positive-def...
2805555,0,0,0,0,0,0,0,0,1,1,<linear-algebra><group-theory><finite-groups><...,1,Is the point group of a discrete group also di...
2805650,0,0,0,0,0,0,0,0,2,2,<linear-algebra><matrices><algebra-precalculus...,2,Show that this is not true: $\left\langle\vec{...
2805691,0,0,0,0,0,0,0,0,1,1,<linear-algebra><matrices>,1,Let $ A\in M_n(\mathbb{C}) $ be an invertible ...
2805794,0,0,0,0,0,0,0,0,3,3,<linear-algebra><matrices><symmetric-matrices>...,-1,Adding matrices to their transpose
2805768,0,0,0,0,0,0,0,0,2,2,<linear-algebra><convex-optimization><semidefi...,2,Maximizing $\mbox{Tr}(MX)$ over $X \succeq 0$ ...
2805891,0,0,0,0,0,0,0,0,2,2,<commutative-algebra><tensor-products><multili...,2,Proof that the given sequence is exact
2805915,0,0,0,0,0,0,0,0,1,1,<linear-algebra>,1,Find the monic generators of the ideals
2805926,0,0,0,0,0,0,0,0,1,1,<linear-algebra><matrices><inverse><matrix-equ...,1,Linear Algebra - Find Matrix X
2806066,0,0,0,0,0,0,0,0,1,1,<linear-algebra>,-1,confirm isomorphism
2806072,0,0,0,0,0,0,0,0,2,2,<linear-algebra>,1,Does $AB$ and $BA$ have the same 'number' of e...
2806100,0,0,0,0,0,0,0,0,2,2,<linear-algebra><matrices><determinant>,1,Minimum and maximum value of determinant of $3...

In [156]:
linear_algebra.shape

(49048, 29)

In [157]:
linear_algebra[linear_algebra['upvotes'] > 0].sort_values("upvotes")

,posttypeid,acceptedanswerid,parentid,creationdate,score,viewcount,body,owneruserid,lasteditoruserid,lasteditordisplayname,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,upvotes
id,,,,,,,,,,,,,,,,,,,,,
1344531,1,1344535.0,NaN,2015-06-30 13:25:35.840,1,91.0,<p>Suppose that $A$ is a bounded positive oper...,251493.0,121097.0,None,...,0,0,0,0,0,1,0,0,0,1
944501,1,944526.0,NaN,2014-09-24 16:13:59.573,1,951.0,<p>I want to know the exact definition of full...,137291.0,NaN,None,...,0,0,0,0,0,0,1,0,0,1
944353,1,944356.0,NaN,2014-09-24 13:47:51.593,1,53.0,<p>I have a equation $(-1)^{2m}$=$1$ so for t...,142634.0,NaN,None,...,0,0,0,0,1,0,0,0,0,1
1935093,1,NaN,NaN,2016-09-21 01:49:01.310,1,25.0,"<p>Let $V$ be a vector space, over a field $K$...",270702.0,11667.0,None,...,0,0,0,0,0,0,1,0,0,1
944200,1,944218.0,NaN,2014-09-24 10:14:58.267,1,62.0,<p>The title says it all... I can't see the di...,83955.0,83955.0,None,...,0,0,0,0,1,0,0,0,0,1
1935101,1,NaN,NaN,2016-09-21 01:58:44.667,1,45.0,"<p>Let $a = \left&lt;2,1\right&gt;$ and $b = \...",370857.0,2785.0,None,...,0,0,0,0,0,0,1,0,0,1
944123,1,952696.0,NaN,2014-09-24 08:37:37.110,1,127.0,<p>I came across something in a paper I am not...,175550.0,175550.0,None,...,0,0,0,0,1,0,0,0,0,1
944115,1,944120.0,NaN,2014-09-24 08:24:13.700,0,45.0,"<blockquote>\n <p>$A: n \times n$, $B: n \tim...",178078.0,NaN,None,...,0,0,0,0,1,0,0,0,0,1
944042,1,944051.0,NaN,2014-09-24 06:52:40.323,1,325.0,"<p>In “Linear Algebra Done Right” by Axler, wh...",51731.0,NaN,None,...,0,0,0,0,1,0,0,0,0,1
1935191,1,1935264.0,NaN,2016-09-21 03:29:03.930,1,86.0,<p>I was doing some exercises of linear functi...,369308.0,22857.0,None,...,0,0,0,0,0,0,1,0,0,1
944767,1,NaN,NaN,2014-09-24 19:50:53.393,1,311.0,<p>What are useful books on Linear ALgeb...,131379.0,8297.0,None,...,0,0,0,0,1,0,0,0,0,1
1935202,1,NaN,NaN,2016-09-21 03:33:19.843,-1,104.0,<p>How do I prove invertible matrix is diagona...,41872.0,NaN,None,...,0,0,0,0,0,0,1,0,0,1
943903,1,NaN,NaN,2014-09-24 04:30:16.343,1,306.0,<p>I have been working on this question and I ...,177796.0,NaN,None,...,0,0,0,0,1,0,0,0,0,1
1935540,1,1935649.0,NaN,2016-09-21 11:34:45.890,1,56.0,<p>Is there any simple method to prove that th...,276347.0,276347.0,None,...,0,0,0,0,0,0,1,0,0,1
943755,1,943756.0,NaN,2014-09-24 01:31:47.150,1,78.0,<p>Show $(ac)^2+(bd)^2+(bc)^2+(ad)^2=1$ if $a^...,178078.0,NaN,None,...,0,0,0,0,1,0,0,0,0,1
943612,1,943699.0,NaN,2014-09-23 23:05:13.573,1,148.0,<p>Suppose that $B$ and $A$ are symmetric matr...,136641.0,136641.0,None,...,0,0,0,0,1,0,0,0,0,1
943426,1,943470.0,NaN,2014-09-23 20:47:05.297,1,18.0,<p>I will be very grateful if someone helps me...,136641.0,136641.0,None,...,0,0,0,0,1,0,0,0,0,1
943382,1,943999.0,NaN,2014-09-23 20:11:02.363,1,46.0,<p>I had a question. Suppose you have a vector...,130587.0,NaN,None,...,0,0,0,0,1,0,0,0,0,1
943367,1,NaN,NaN,2014-09-23 19:59:51.310,2,76.0,"<p>As a follow up to my question on <a href=""h...",8964.0,-1.0,None,...,0,0,0,0,1,0,0,0,0,1
943326,1,NaN,NaN,2014-09-23 19:22:24.790,-2,679.0,<p>The vector $\dfrac{x\cdot y}{y\cdot y}y$ is...,175850.0,NaN,user147263,...,0,0,0,0,0,0,1,0,0,1
943299,1,943320.0,NaN,2014-09-23 18:52:24.803,1,212.0,<p>$n=(2^{2014}-1)/3$ what is the remainder wh...,142634.0,NaN,None,...,0,0,0,0,1,0,0,0,0,1
944003,1,944010.0,NaN,2014-09-24 06:11:14.817,1,569.0,<p>$A =\left(\begin{array}{ccc}\n0 &amp; 1 &am...,178078.0,93144.0,None,...,0,0,0,0,1,0,0,0,0,1
944840,1,944870.0,NaN,2014-09-24 20:52:22.770,0,2011.0,"<p>For vectors u, w, and v in a vector space V...",129313.0,129313.0,None,...,0,0,0,0,1,0,0,0,0,1
944927,1,NaN,NaN,2014-09-24 22:11:55.130,1,7208.0,"<ol>\n<li>$v_1=(1,1,0)$</li>\n<li>$v_2=(1,2,1)...",173809.0,NaN,None,...,0,0,0,0,1,0,0,0,0,1
945105,1,945130.0,NaN,2014-09-25 01:01:57.187,1,30.0,<p>If I say there is a linear map <strong>T</s...,176051.0,NaN,None,...,0,0,0,0,1,0,0,0,0,1
946805,1,NaN,NaN,2014-09-26 10:28:04.247,1,36.0,<p>I came across this theorem that says:</p>\n...,139772.0,NaN,None,...,0,0,0,0,1,0,0,0,0,1
946740,1,NaN,NaN,2014-09-26 09:03:44.857,1,71.0,<p>I need to diagonalise the following symmetr...,104750.0,104750.0,None,...,0,0,0,0,1,0,0,0,0,1
946568,1,946606.0,NaN,2014-09-26 04:52:54.517,0,686.0,"<p>If $A$ is a nilpotent matrix, then how to ...",175698.0,175698.0,None,...,0,0,0,0,1,0,0,0,0,1
946535,1,NaN,NaN,2014-09-26 04:21:19.787,1,55.0,<p>Let $A\in\operatorname{M}_n(F)$. How to pro...,175182.0,175182.0,None,...,0,0,0,0,1,0,0,0,0,1
1934344,1,NaN,NaN,2016-09-20 15:27:57.850,1,35.0,"<p>For what values of $a_1,a_2,...,a_n$ is the...",369532.0,140308.0,None,...,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1279861,1,1280243.0,NaN,2015-05-13 06:35:38.820,85,5382.0,<p>It is well known that for invertible matric...,62839.0,NaN,None,...,0,0,0,0,0,69,7,6,1,83
180418,1,476311.0,NaN,2012-08-08 21:03:46.890,86,156772.0,<p>I have one triangle in 3d space that I am t...,22716.0,NaN,None,...,0,0,4,6,7,14,18,18,17,84
1093696,1,1093720.0,NaN,2015-01-07 00:00:29.827,84,20315.0,<p>Assuming that we can't bold our variables (...,168326.0,NaN,None,...,0,0,0,0,0,58,13,11,3,85
645672,1,NaN,NaN,2014-01-21 00:55:31.120,86,34059.0,<p>I understand that a vector has direction an...,109559.0,168764.0,None,...,0,0,0,0,45,9,15,11,7,87
275310,1,NaN,NaN,2013-01-10 16:49:01.790,90,70600.0,<p>I am a bit confused. What is the difference...,34790.0,1543.0,None,...,0,0,0,3,8,14,21,30,12,88
2624411,1,NaN,NaN,2018-01-28 02:37:22.740,88,6623.0,"<p>It seems, at times, that physicists and mat...",340064.0,9260.0,None,...,0,0,0,0,0,0,0,0,88,88
17776,1,17780.0,NaN,2011-01-16 20:48:26.543,92,155221.0,<p>I have two square matrices - $A$ and $B$. $...,4811.0,498.0,None,...,0,4,6,6,15,13,21,15,9,89
2707046,1,NaN,NaN,2018-03-25 06:28:22.650,91,4420.0,<p>Consider the class of rational functions th...,536255.0,138538.0,None,...,0,0,0,0,0,0,0,0,91,91
256682,1,256695.0,NaN,2012-12-12 00:04:05.370,102,97131.0,<p>Simply as the title says. I've done some re...,52705.0,52705.0,None,...,0,0,31,9,12,8,13,18,7,98
945871,1,945918.0,NaN,2014-09-25 16:43:17.473,103,89614.0,<p>I am trying to wrap my head around back-pro...,138387.0,251017.0,None,...,0,0,0,0,2,9,33,44,11,99
37398,1,NaN,NaN,2011-05-06 12:02:28.840,108,25256.0,<p>I can follow the definition of the transpos...,10574.0,8297.0,None,...,0,16,5,6,10,6,22,24,13,102
6244,1,6247.0,NaN,2010-10-07 02:10:17.703,108,23319.0,<p>It would seem that one way of proving this ...,647.0,121097.0,None,...,7,9,9,11,11,13,16,14,13,103
2608566,1,NaN,NaN,2018-01-17 01:34:11.230,107,9865.0,<p>The dot product of vectors $\mathbf{a}$ and...,39454.0,39454.0,None,...,0,0,0,0,0,0,0,0,111,111
4335,1,4341.0,NaN,2010-09-09 14:51:35.530,114,135662.0,<p>I'm starting a very long quest to learn abo...,NaN,2264.0,None,...,2,3,7,12,18,21,24,17,9,113
82467,1,82471.0,NaN,2011-11-15 21:08:52.133,123,153831.0,"<p>Can someone point me to a paper, or show he...",8616.0,8616.0,None,...,0,0,0,4,7,27,25,28,23,114
243533,1,243541.0,NaN,2012-11-24 04:18:29.993,126,93023.0,<p>I'm learning multivariate analysis and I ha...,43252.0,43252.0,None,...,0,0,12,5,17,16,19,37,14,120
1834686,1,1834697.0,NaN,2016-06-21 16:28:33.283,120,34121.0,<p>During a year and half of studying Linear A...,262321.0,171583.0,None,...,0,0,0,0,0,0,107,7,6,120
478212,1,478222.0,NaN,2013-08-28 14:52:22.303,128,25568.0,<p>I am teaching an elementary student. He has...,26975.0,471884.0,None,...,0,0,0,67,10,13,15,13,9,127
175561,1,175567.0,NaN,2012-07-26 18:04:56.930,133,8719.0,<p>$$\begin{bmatrix} 1235 &amp;2344 &amp;1234 ...,36514.0,339790.0,None,...,0,0,12,14,20,27,31,18,10,132
73144,1,73150.0,NaN,2011-10-16 20:40:26.370,134,10091.0,"<p>Well, I've heard that a ""cubic"" matrix woul...",17751.0,498.0,None,...,0,52,14,18,10,10,12,12,4,132
3749,1,3755.0,NaN,2010-08-31 22:47:52.857,157,23621.0,"<p>When I first took linear algebra, we never ...",249.0,168764.0,None,...,6,1,12,17,11,18,37,27,21,150
21792,1,21795.0,NaN,2011-02-13 04:37:10.230,157,38869.0,<p>Let $ V $ be a normed vector space (over $\...,3537.0,19009.0,None,...,0,22,4,17,15,24,26,27,15,150
258736,1,NaN,NaN,2012-12-14 15:37:08.767,170,8898.0,<p>Let </p>\n\n<p>$$\nH=\left(\begin{array}{cc...,53115.0,53115.0,None,...,0,0,4,8,11,22,28,51,34,158
1634488,1,1634551.0,NaN,2016-01-31 13:56:31.480,166,7329.0,<p>Suppose I have a square matrix $\mathsf{A}$...,266764.0,395886.0,None,...,0,0,0,0,0,0,137,20,7,164
1541800,1,1541823.0,NaN,2015-11-22 21:43:10.693,181,12115.0,<p>I happened to stumble upon the following ma...,136368.0,339790.0,None,...,0,0,0,0,0,138,23,10,7,178
23312,1,23325.0,NaN,2011-02-23 02:31:25.610,202,133173.0,<p>What is the importance of eigenvalues/eigen...,6764.0,13854.0,None,...,0,16,8,17,26,30,50,32,21,200
3852,1,3860.0,NaN,2010-09-02 07:04:36.537,236,46963.0,<blockquote>\n <p>If $A$ and $B$ are square m...,1674.0,339790.0,user3302,...,12,14,12,13,28,28,37,51,32,227
860294,1,NaN,NaN,2014-07-08 16:41:00.807,246,11800.0,<p><strong>Question:</strong></p>\n\n<blockquo...,94077.0,221811.0,None,...,0,0,0,0,72,35,81,53,10,251
3869,1,3871.0,NaN,2010-09-02 11:52:10.883,298,143407.0,"<p>Singular value decomposition (<a href=""http...",1680.0,339790.0,None,...,7,10,18,41,36,64,53,42,17,288
668,1,669.0,NaN,2010-07-25 02:25:11.593,549,101331.0,"<p>In my linear algebra class, we just talked ...",76.0,339790.0,None,...,25,42,42,53,64,92,91,87,38,534

In [162]:
linear_algebra.sort_values(['upvotes', 'score'], ascending=False)[["upvotes","score"]]

         upvotes  score
id
668          534    549
3869         288    298
860294       251    246
3852         227    236
23312        200    202
1541800      178    181
1634488      164    166
258736       158    170
3749         150    157
21792        150    157
73144        132    134
175561       132    133
478212       127    128
243533       120    126
1834686      120    120
82467        114    123
4335         113    114
2608566      111    107
6244         103    108
37398        102    108
945871        99    103
256682        98    102
2707046       91     91
17776         89     92
275310        88     90
2624411       88     88
645672        87     86
1093696       85     84
180418        84     86
23596         83     85
...          ...    ...
2568562        1     -3
2574059        1     -3
2578493        1     -3
2593029        1     -3
2597771        1     -3
2686463        1     -3
2726166        1     -3
2773314        1     -3
2788777        1     -3
2802760        1     -3
170598         1     -4
220137         1     -4
556579         1     -4
1168990        1     -4
1301412        1     -4
1506333        1     -4
1711612        1     -4
1863885        1     -4
1911918        1     -4
2209388        1     -4
2360409        1     -4
2426910        1     -4
2456030        1     -4
2486412        1     -4
2729088        1     -4
1804467        1     -5
1929419        1     -5
2617757        1     -5
1289225        1     -6
2169009        1     -6

[49048 rows x 2 columns]

In [ ]:
# for the above need to calculate slope.